// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    flchain_dummy
    (
        init => init
        upgrade => upgrade
        generate_random_dna => generate_random_dna
        retrieve_client_id_by_address => retrieve_client_id_by_address
        retrieve_address_by_client_id => retrieve_address_by_client_id
        store_ipfs_file => store_ipfs_file
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
